
package lsc.businesslogic.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LSCLogic", targetNamespace = "http://ws.businesslogic.lsc/", wsdlLocation = "http://localhost:3333/lsc/ws/LSCLogic?wsdl")
public class LSCLogic_Service
    extends Service
{

    private final static URL LSCLOGIC_WSDL_LOCATION;
    private final static WebServiceException LSCLOGIC_EXCEPTION;
    private final static QName LSCLOGIC_QNAME = new QName("http://ws.businesslogic.lsc/", "LSCLogic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3333/lsc/ws/LSCLogic?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LSCLOGIC_WSDL_LOCATION = url;
        LSCLOGIC_EXCEPTION = e;
    }

    public LSCLogic_Service() {
        super(__getWsdlLocation(), LSCLOGIC_QNAME);
    }

    public LSCLogic_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LSCLOGIC_QNAME, features);
    }

    public LSCLogic_Service(URL wsdlLocation) {
        super(wsdlLocation, LSCLOGIC_QNAME);
    }

    public LSCLogic_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LSCLOGIC_QNAME, features);
    }

    public LSCLogic_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LSCLogic_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LSCLogic
     */
    @WebEndpoint(name = "LSCLogicImplPort")
    public LSCLogic getLSCLogicImplPort() {
        return super.getPort(new QName("http://ws.businesslogic.lsc/", "LSCLogicImplPort"), LSCLogic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LSCLogic
     */
    @WebEndpoint(name = "LSCLogicImplPort")
    public LSCLogic getLSCLogicImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.businesslogic.lsc/", "LSCLogicImplPort"), LSCLogic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LSCLOGIC_EXCEPTION!= null) {
            throw LSCLOGIC_EXCEPTION;
        }
        return LSCLOGIC_WSDL_LOCATION;
    }

}
